# Copy this file to .github/workflows/tasksmd-sync.yml in your repository
name: Sync TASKS.md

on:
  push:
    branches: [main]
    paths: ['TASKS.md']
  pull_request:
    paths: ['TASKS.md']

jobs:
  sync-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: harmoniqs/tasksmd-sync@main
        with:
          tasks-file: TASKS.md
          org: harmoniqs
          project-number: '1'  # <-- Update to your project board number
          repo-label: ${{ github.event.repository.name }}
          github-token: ${{ secrets.PROJECTS_TOKEN }}
          # Dry-run on PRs, live sync on push to main
          dry-run: ${{ github.event_name == 'pull_request' }}
